/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */

public class SeatSelection extends javax.swing.JFrame {

    /**
     * Creates new form SeatSelection
     */
    private int Scount = 0;
   private int Gcount = 0;
   private int Pcount = 0;
    public SeatSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transparentPanel = new javax.swing.JPanel();
        S2 = new javax.swing.JToggleButton();
        G1 = new javax.swing.JToggleButton();
        S1 = new javax.swing.JToggleButton();
        S3 = new javax.swing.JToggleButton();
        S4 = new javax.swing.JToggleButton();
        S8 = new javax.swing.JToggleButton();
        S7 = new javax.swing.JToggleButton();
        S6 = new javax.swing.JToggleButton();
        S5 = new javax.swing.JToggleButton();
        S10 = new javax.swing.JToggleButton();
        S9 = new javax.swing.JToggleButton();
        G2 = new javax.swing.JToggleButton();
        G3 = new javax.swing.JToggleButton();
        G4 = new javax.swing.JToggleButton();
        G6 = new javax.swing.JToggleButton();
        G5 = new javax.swing.JToggleButton();
        G10 = new javax.swing.JToggleButton();
        G9 = new javax.swing.JToggleButton();
        G8 = new javax.swing.JToggleButton();
        G7 = new javax.swing.JToggleButton();
        P4 = new javax.swing.JToggleButton();
        P5 = new javax.swing.JToggleButton();
        P6 = new javax.swing.JToggleButton();
        P10 = new javax.swing.JToggleButton();
        P9 = new javax.swing.JToggleButton();
        P8 = new javax.swing.JToggleButton();
        P7 = new javax.swing.JToggleButton();
        display = new javax.swing.JTextField();
        P11 = new javax.swing.JToggleButton();
        P12 = new javax.swing.JToggleButton();
        P13 = new javax.swing.JToggleButton();
        P14 = new javax.swing.JToggleButton();
        P15 = new javax.swing.JToggleButton();
        P16 = new javax.swing.JToggleButton();
        P17 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        silver = new javax.swing.JLabel();
        P3 = new javax.swing.JToggleButton();
        platinum = new javax.swing.JLabel();
        gold = new javax.swing.JLabel();
        P2 = new javax.swing.JToggleButton();
        P1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transparentPanel.setBackground(new java.awt.Color(44, 62, 80));

        S2.setBackground(new java.awt.Color(209, 209, 209));
        S2.setText("102");
        S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S2ActionPerformed(evt);
            }
        });

        G1.setBackground(new java.awt.Color(209, 209, 209));
        G1.setText("111");
        G1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G1ActionPerformed(evt);
            }
        });

        S1.setBackground(new java.awt.Color(209, 209, 209));
        S1.setText("101");
        S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S1ActionPerformed(evt);
            }
        });

        S3.setBackground(new java.awt.Color(209, 209, 209));
        S3.setText("103");
        S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S3ActionPerformed(evt);
            }
        });

        S4.setBackground(new java.awt.Color(209, 209, 209));
        S4.setText("104");
        S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S4ActionPerformed(evt);
            }
        });

        S8.setBackground(new java.awt.Color(209, 209, 209));
        S8.setText("108");
        S8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S8ActionPerformed(evt);
            }
        });

        S7.setBackground(new java.awt.Color(209, 209, 209));
        S7.setText("107");
        S7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S7ActionPerformed(evt);
            }
        });

        S6.setBackground(new java.awt.Color(209, 209, 209));
        S6.setText("106");
        S6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S6ActionPerformed(evt);
            }
        });

        S5.setBackground(new java.awt.Color(209, 209, 209));
        S5.setText("105");
        S5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S5ActionPerformed(evt);
            }
        });

        S10.setBackground(new java.awt.Color(209, 209, 209));
        S10.setText("110");
        S10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S10ActionPerformed(evt);
            }
        });

        S9.setBackground(new java.awt.Color(209, 209, 209));
        S9.setText("109");
        S9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S9ActionPerformed(evt);
            }
        });

        G2.setBackground(new java.awt.Color(209, 209, 209));
        G2.setText("112");
        G2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G2ActionPerformed(evt);
            }
        });

        G3.setBackground(new java.awt.Color(209, 209, 209));
        G3.setText("113");
        G3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G3ActionPerformed(evt);
            }
        });

        G4.setBackground(new java.awt.Color(209, 209, 209));
        G4.setText("114");
        G4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G4ActionPerformed(evt);
            }
        });

        G6.setBackground(new java.awt.Color(235, 207, 84));
        G6.setText("116");
        G6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G6ActionPerformed(evt);
            }
        });

        G5.setBackground(new java.awt.Color(209, 209, 209));
        G5.setText("115");
        G5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G5ActionPerformed(evt);
            }
        });

        G10.setBackground(new java.awt.Color(235, 207, 84));
        G10.setText("120");
        G10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G10ActionPerformed(evt);
            }
        });

        G9.setBackground(new java.awt.Color(235, 207, 84));
        G9.setText("119");
        G9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G9ActionPerformed(evt);
            }
        });

        G8.setBackground(new java.awt.Color(235, 207, 84));
        G8.setText("118");
        G8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G8ActionPerformed(evt);
            }
        });

        G7.setBackground(new java.awt.Color(235, 207, 84));
        G7.setText("117");
        G7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G7ActionPerformed(evt);
            }
        });

        P4.setBackground(new java.awt.Color(235, 207, 84));
        P4.setText("124");
        P4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P4ActionPerformed(evt);
            }
        });

        P5.setBackground(new java.awt.Color(235, 207, 84));
        P5.setText("125");
        P5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P5ActionPerformed(evt);
            }
        });

        P6.setBackground(new java.awt.Color(235, 207, 84));
        P6.setText("126");
        P6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P6ActionPerformed(evt);
            }
        });

        P10.setBackground(new java.awt.Color(228, 0, 125));
        P10.setText("129");
        P10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P10ActionPerformed(evt);
            }
        });

        P9.setBackground(new java.awt.Color(228, 0, 125));
        P9.setText("130");
        P9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P9ActionPerformed(evt);
            }
        });

        P8.setBackground(new java.awt.Color(228, 0, 125));
        P8.setText("128");
        P8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P8ActionPerformed(evt);
            }
        });

        P7.setBackground(new java.awt.Color(235, 207, 84));
        P7.setText("127");
        P7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P7ActionPerformed(evt);
            }
        });

        display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        P11.setBackground(new java.awt.Color(228, 0, 125));
        P11.setText("132");
        P11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P11ActionPerformed(evt);
            }
        });

        P12.setBackground(new java.awt.Color(228, 0, 125));
        P12.setText("131");
        P12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P12ActionPerformed(evt);
            }
        });

        P13.setBackground(new java.awt.Color(228, 0, 125));
        P13.setText("133");
        P13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P13ActionPerformed(evt);
            }
        });

        P14.setBackground(new java.awt.Color(228, 0, 125));
        P14.setText("134");
        P14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P14ActionPerformed(evt);
            }
        });

        P15.setBackground(new java.awt.Color(228, 0, 125));
        P15.setText("135");
        P15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P15ActionPerformed(evt);
            }
        });

        P16.setBackground(new java.awt.Color(228, 0, 125));
        P16.setText("136");
        P16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P16ActionPerformed(evt);
            }
        });

        P17.setBackground(new java.awt.Color(228, 0, 125));
        P17.setText("137");
        P17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P17ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(248, 148, 6));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reserve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/Images/seat.PNG"))); // NOI18N

        javax.swing.GroupLayout transparentPanelLayout = new javax.swing.GroupLayout(transparentPanel);
        transparentPanel.setLayout(transparentPanelLayout);
        transparentPanelLayout.setHorizontalGroup(
            transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transparentPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jButton1))))
                    .addGroup(transparentPanelLayout.createSequentialGroup()
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(transparentPanelLayout.createSequentialGroup()
                                    .addComponent(S9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(S10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(transparentPanelLayout.createSequentialGroup()
                                    .addComponent(S7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(S8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(S5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(S6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(S4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transparentPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addComponent(G8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(G10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addComponent(G6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(P5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transparentPanelLayout.createSequentialGroup()
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(P9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(P14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(P12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(P8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(P10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(P11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(P15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(P17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(P16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(P13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(112, 112, 112))))
        );
        transparentPanelLayout.setVerticalGroup(
            transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparentPanelLayout.createSequentialGroup()
                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transparentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(P4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transparentPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(G6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(G7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))))
                    .addGroup(transparentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transparentPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(G9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(P5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(G8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(P6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transparentPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transparentPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(S6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(S5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(S8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transparentPanelLayout.createSequentialGroup()
                        .addComponent(P9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(transparentPanelLayout.createSequentialGroup()
                        .addGroup(transparentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(S9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        silver.setBackground(new java.awt.Color(2, 71, 254));
        silver.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        silver.setForeground(new java.awt.Color(255, 255, 255));
        silver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        silver.setText("Paltinum");

        P3.setBackground(new java.awt.Color(235, 207, 84));
        P3.setText("123");
        P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P3ActionPerformed(evt);
            }
        });

        platinum.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        platinum.setForeground(new java.awt.Color(255, 255, 255));
        platinum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        platinum.setText("Silver ");

        gold.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        gold.setForeground(new java.awt.Color(255, 255, 255));
        gold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gold.setText("Gold ");

        P2.setBackground(new java.awt.Color(235, 207, 84));
        P2.setText("122");
        P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2ActionPerformed(evt);
            }
        });

        P1.setBackground(new java.awt.Color(235, 207, 84));
        P1.setText("121");
        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 451, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(platinum, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(silver, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gold, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(transparentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(platinum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(gold, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(silver, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(transparentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S2ActionPerformed

        String data;
        if (S2.isSelected()){
            data =  S2.getText();
            display.setText(data);
            S2.setBackground(Color.red);
            Gcount++;
        }else{
            S2.setBackground(new Color(209,209,209,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_S2ActionPerformed

    private void G1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G1ActionPerformed

        String data;
        if (G1.isSelected()){
            data =  G1.getText();
            display.setText(data);
            G1.setBackground(Color.red);
            Gcount++;
        }else{
            G1.setBackground(new Color(235,207,84,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_G1ActionPerformed

    private void P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2ActionPerformed

        String data;
        if (P2.isSelected()){
            data =  P2.getText();
            display.setText(data);
            P2.setBackground(Color.red);
            Scount++;
        }else{
            P2.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P2ActionPerformed

    private void S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S1ActionPerformed
        String data;
        if (S1.isSelected()){
            data =  S1.getText();
            display.setText(data);

            S1.setBackground(Color.red);
            Gcount++;

        }else{
            S1.setBackground(new Color(209,209,209,100));

            display.setText("");
            Gcount--;

        }
    }//GEN-LAST:event_S1ActionPerformed

    private void S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S3ActionPerformed

        String data;
        if (S3.isSelected()){
            data =  S3.getText();
            display.setText(data);
            S3.setBackground(Color.red);
            Gcount++;
        }else{
            S3.setBackground(new Color(209,209,209,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_S3ActionPerformed

    private void S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S4ActionPerformed

        String data;
        if (S4.isSelected()){
            data =  S4.getText();
            display.setText(data);
            S4.setBackground(Color.red);
            Gcount++;
        }else{
            S4.setBackground(new Color(209,209,209,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_S4ActionPerformed

    private void S8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S8ActionPerformed

        String data;
        if (S8.isSelected()){
            data =  S8.getText();
            display.setText(data);
            S8.setBackground(Color.red);
            Gcount++;
        }else{
            S8.setBackground(new Color(209,209,209,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_S8ActionPerformed

    private void S7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S7ActionPerformed

        String data;
        if (S7.isSelected()){
            data =  S7.getText();
            display.setText(data);
            S7.setBackground(Color.red);
            Gcount++;
        }else{
            S7.setBackground(new Color(209,209,209,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_S7ActionPerformed

    private void S6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S6ActionPerformed

        String data;
        if (S6.isSelected()){
            data =  S6.getText();
            display.setText(data);
            S6.setBackground(Color.red);
            Gcount++;
        }else{

            S6.setBackground(new Color(209,209,209,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_S6ActionPerformed

    private void S5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S5ActionPerformed

        String data;
        if (S5.isSelected()){
            data =  S5.getText();
            display.setText(data);
            S5.setBackground(Color.red);
            Gcount++;
        }else{
            S5.setBackground(new Color(209,209,209,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_S5ActionPerformed

    private void S10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S10ActionPerformed

        String data;
        if (S10.isSelected()){
            data =  S10.getText();
            display.setText(data);
            S10.setBackground(Color.red);
            Gcount++;
        }else{
            S10.setBackground(new Color(209,209,209,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_S10ActionPerformed

    private void S9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S9ActionPerformed

        String data;
        if (S9.isSelected()){
            data =  S9.getText();
            display.setText(data);
            S9.setBackground(Color.red);
            Scount++;
        }else{
            S9.setBackground(new Color(209,209,209,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_S9ActionPerformed

    private void G2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G2ActionPerformed

        String data;
        if (G2.isSelected()){
            data =  G2.getText();
            display.setText(data);
            G2.setBackground(Color.red);
            Gcount++;
        }else{
            G2.setBackground(new Color(235,207,84,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_G2ActionPerformed

    private void G3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G3ActionPerformed

        String data;
        if (G3.isSelected()){
            data =  G3.getText();
            display.setText(data);
            G3.setBackground(Color.red);
            Gcount++;
        }else{
            G3.setBackground(new Color(235,207,84,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_G3ActionPerformed

    private void G4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G4ActionPerformed

        String data;
        if (G4.isSelected()){
            data =  G4.getText();
            display.setText(data);
            G4.setBackground(Color.red);
            Gcount++;
        }else{
            G4.setBackground(new Color(235,207,84,100));

            display.setText("");
            Gcount--;
        }
    }//GEN-LAST:event_G4ActionPerformed

    private void G6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G6ActionPerformed

        String data;
        if (G6.isSelected()){
            data =  G6.getText();
            display.setText(data);
            G6.setBackground(Color.red);
            Scount++;
        }else{
            G6.setBackground(new Color(235,207,84,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_G6ActionPerformed

    private void G5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G5ActionPerformed

        String data;
        if (G5.isSelected()){
            data =  G5.getText();
            display.setText(data);
            G5.setBackground(Color.red);
            Gcount++;
        }else{
            G5.setBackground(new Color(235,207,84,100));

            display.setText("");
            Gcount--;
        }

    }//GEN-LAST:event_G5ActionPerformed

    private void G10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G10ActionPerformed

        String data;
        if (G10.isSelected()){
            data =  G10.getText();
            display.setText(data);
            G10.setBackground(Color.red);
            Scount++;
        }else{
            G10.setBackground(new Color(235,207,84,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_G10ActionPerformed

    private void G9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G9ActionPerformed

        String data;
        if (G9.isSelected()){
            data =  G9.getText();
            display.setText(data);
            G9.setBackground(Color.red);
            Scount++;
        }else{
            G9.setBackground(new Color(235,207,84,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_G9ActionPerformed

    private void G8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G8ActionPerformed

        String data;
        if (G8.isSelected()){
            data =  G8.getText();
            display.setText(data);
            G8.setBackground(Color.red);
            Scount++;
        }else{
            G8.setBackground(new Color(235,207,84,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_G8ActionPerformed

    private void G7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G7ActionPerformed

        String data;
        if (G7.isSelected()){
            data =  G7.getText();
            display.setText(data);
            G7.setBackground(Color.red);
            Scount++;
        }else{
            G7.setBackground(new Color(235,207,84,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_G7ActionPerformed

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed

        String data;
        if (P1.isSelected()){
            data =  P1.getText();
            display.setText(data);
            P1.setBackground(Color.red);
            Scount++;
        }else{
            P1.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P1ActionPerformed

    private void P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P3ActionPerformed

        String data;
        if (P3.isSelected()){
            data =  P3.getText();
            display.setText(data);
            P3.setBackground(Color.red);
            Scount++;
        }else{
            P3.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P3ActionPerformed

    private void P4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P4ActionPerformed

        String data;
        if (P4.isSelected()){
            data =  P4.getText();
            display.setText(data);
            P4.setBackground(Color.red);
            Scount++;
        }else{
            P4.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P4ActionPerformed

    private void P5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P5ActionPerformed

        String data;
        if (P5.isSelected()){
            data =  P5.getText();
            display.setText(data);
            P5.setBackground(Color.red);
            Scount++;
        }else{
            P5.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P5ActionPerformed

    private void P6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P6ActionPerformed

        String data;
        if (P6.isSelected()){
            data =  P6.getText();
            display.setText(data);
            P6.setBackground(Color.red);
            Scount++;
        }else{
            P6.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P6ActionPerformed

    private void P10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P10ActionPerformed

        String data;
        if (P10.isSelected()){
            data =  P10.getText();
            display.setText(data);
            P10.setBackground(Color.red);
            Pcount++;
        }else{
            P10.setBackground(new Color(228,0,125,100));

            display.setText("");
            Pcount--;
        }
    }//GEN-LAST:event_P10ActionPerformed

    private void P9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P9ActionPerformed

        String data;
        if (P9.isSelected()){
            data =  P9.getText();
            display.setText(data);
            P9.setBackground(Color.red);
            Pcount++;
        }else{
            P9.setBackground(new Color(228,0,125,100));

            display.setText("");
            Pcount--;
        }
    }//GEN-LAST:event_P9ActionPerformed

    private void P8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P8ActionPerformed

        String data;
        if (P8.isSelected()){
            data =  P8.getText();
            display.setText(data);
            P8.setBackground(Color.red);
            Pcount++;
        }else{
            P8.setBackground(new Color(228,0,125,100));

            display.setText("");
            Pcount--;
        }
    }//GEN-LAST:event_P8ActionPerformed

    private void P7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P7ActionPerformed

        String data;
        if (P7.isSelected()){
            data =  P7.getText();
            display.setText(data);

            P7.setBackground(Color.red);
            Scount++;

        }

        else{
            P7.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P7ActionPerformed

    private void P11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P11ActionPerformed
        // TODO add your handling code here:
        String data;
        if (P11.isSelected()){
            data =  P11.getText();
            display.setText(data);

            P11.setBackground(Color.red);
            Scount++;

        }

        else{
            P11.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
      
    }//GEN-LAST:event_P11ActionPerformed

    private void P12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P12ActionPerformed
        // TODO add your handling code here:
         String data;
        if (P12.isSelected()){
            data =  P12.getText();
            display.setText(data);

            P12.setBackground(Color.red);
            Scount++;

        }

        else{
            P12.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
      
    }//GEN-LAST:event_P12ActionPerformed

    private void P13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P13ActionPerformed
        // TODO add your handling code here:
        String data;
        if (P13.isSelected()){
            data =  P13.getText();
            display.setText(data);

            P13.setBackground(Color.red);
            Scount++;

        }

        else{
            P13.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P13ActionPerformed

    private void P14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P14ActionPerformed
        // TODO add your handling code here:
        String data;
        if (P14.isSelected()){
            data =  P14.getText();
            display.setText(data);

            P14.setBackground(Color.red);
            Scount++;

        }

        else{
            P14.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
      
    }//GEN-LAST:event_P14ActionPerformed

    private void P15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P15ActionPerformed
        // TODO add your handling code here:
        String data;
        if (P15.isSelected()){
            data =  P15.getText();
            display.setText(data);

            P15.setBackground(Color.red);
            Scount++;

        }

        else{
            P15.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P15ActionPerformed

    private void P16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P16ActionPerformed
        // TODO add your handling code here:
        String data;
        if (P16.isSelected()){
            data =  P16.getText();
            display.setText(data);

            P16.setBackground(Color.red);
            Scount++;

        }

        else{
            P16.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P16ActionPerformed

    private void P17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P17ActionPerformed
        // TODO add your handling code here:
        String data;
        if (P17.isSelected()){
            data =  P17.getText();
            display.setText(data);

            P17.setBackground(Color.red);
            Scount++;

        }

        else{
            P17.setBackground(new Color(228,0,125,100));

            display.setText("");
            Scount--;
        }
    }//GEN-LAST:event_P17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Seats reserved");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton G1;
    private javax.swing.JToggleButton G10;
    private javax.swing.JToggleButton G2;
    private javax.swing.JToggleButton G3;
    private javax.swing.JToggleButton G4;
    private javax.swing.JToggleButton G5;
    private javax.swing.JToggleButton G6;
    private javax.swing.JToggleButton G7;
    private javax.swing.JToggleButton G8;
    private javax.swing.JToggleButton G9;
    private javax.swing.JToggleButton P1;
    private javax.swing.JToggleButton P10;
    private javax.swing.JToggleButton P11;
    private javax.swing.JToggleButton P12;
    private javax.swing.JToggleButton P13;
    private javax.swing.JToggleButton P14;
    private javax.swing.JToggleButton P15;
    private javax.swing.JToggleButton P16;
    private javax.swing.JToggleButton P17;
    private javax.swing.JToggleButton P2;
    private javax.swing.JToggleButton P3;
    private javax.swing.JToggleButton P4;
    private javax.swing.JToggleButton P5;
    private javax.swing.JToggleButton P6;
    private javax.swing.JToggleButton P7;
    private javax.swing.JToggleButton P8;
    private javax.swing.JToggleButton P9;
    private javax.swing.JToggleButton S1;
    private javax.swing.JToggleButton S10;
    private javax.swing.JToggleButton S2;
    private javax.swing.JToggleButton S3;
    private javax.swing.JToggleButton S4;
    private javax.swing.JToggleButton S5;
    private javax.swing.JToggleButton S6;
    private javax.swing.JToggleButton S7;
    private javax.swing.JToggleButton S8;
    private javax.swing.JToggleButton S9;
    private javax.swing.JTextField display;
    private javax.swing.JLabel gold;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel platinum;
    private javax.swing.JLabel silver;
    private javax.swing.JPanel transparentPanel;
    // End of variables declaration//GEN-END:variables
}
